/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringUtilsTest {
    @Test
    public void isPositiveNumber_true() {
        StringUtils classUnderTest = new StringUtils();
        assertEquals(true, classUnderTest.isPositiveNumber("55"), "Positive number test passed");
    }

    @Test
    public void isPositiveNumber_false() {
        StringUtils classUnderTest = new StringUtils();
        assertEquals(false, classUnderTest.isPositiveNumber("-55a"), "Negative number test passed");
    }

    @Test
    public void isPositiveNumber_0case() {
        StringUtils classUnderTest = new StringUtils();

        Exception exception = assertThrows(StringUtils.class, () -> {
            classUnderTest.isPositiveNumber("0");
        });

        String expectedMessage = "Invalid Input: Either 0 or incorrect value entered";
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }

    @Test
    public void isPositiveNumber_nullValue() {
        StringUtils classUnderTest = new StringUtils();

        Exception exception = assertThrows(StringUtils.class, () -> {
            classUnderTest.isPositiveNumber("");
        });

        String expectedMessage = "Invalid Input: Either 0 or incorrect value entered";
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }
}
