/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;

import org.apache.commons.lang3.math.NumberUtils;

public class StringUtils extends RuntimeException {

    StringUtils(){
        super("Invalid Input: Either 0 or incorrect value entered");
    }

    public boolean isPositiveNumber(String str) {

        long temp = NumberUtils.toLong(str);

        if (temp == 0) {
            throw new StringUtils();
        }
        else{
            if(temp > 0){
                return true;
            }
            else{
                return false;
            }
        }
    }
}
